#!/bin/bash
echo "=== AgentFoundry V2 Automated Demo ==="
echo ""

echo "1. Starting AgentFoundry Watch Daemon in background..."
node packages/cli/dist/cli.js watch &
DAEMON_PID=$!

# Give the daemon a few seconds to initialize and take the initial Git snapshot
sleep 4

echo ""
echo "2. Simulating 'Claude Code' waking up..."
# We spawn a node script that just waits for 6 seconds. 
# We path it as 'claude_dummy' so the ProcessMonitor's signature detection thinks it is Claude.
node -e 'setTimeout(() => {}, 6000)' /claude_dummy &
CLAUDE_PID=$!

sleep 2
echo "3. Simulating Claude automatically modifying a file..."
# Append a task so there is a real file diff for the GitTracker to catch
echo "- [ ] Autogenerated demo task by fake AI" >> tasks/todo.md

echo "   Waiting for Claude script to finish running..."
wait $CLAUDE_PID

echo "4. Claude process ended natively."
echo "   Waiting for Daemon to detect process death, calculate Git diffs, and push to SQLite..."
sleep 5

echo "5. Stopping background Daemon..."
kill $DAEMON_PID
sleep 1

echo ""
echo "============================================="
echo "=== 📊 AGENTFOUNDRY SQLITE FINAL DASHBOARD ==="
echo "============================================="
node packages/cli/dist/cli.js stats
echo "============================================="
echo ""
